---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shalev223/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort        # expose on a high port on each node
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080     # <— you can choose any 30000–32767 port
