all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    k3s_servers:
      hosts:
      
        3.90.10.72:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/heave/.ssh/my-ec2-key

    k3s_agents:
      hosts:
        54.224.181.220:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/heave/.ssh/my-ec2-key
        3.210.202.192:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/heave/.ssh/my-ec2-key
    jenkins:
      hosts:
        54.164.236.144:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/heave/.ssh/my-ec2-key