[k3s_servers]
3.90.10.72 ansible_user=ubuntu ansible_ssh_private_key_file=/home/heave/.ssh/my-ec2-key

[k3s_agents]
54.224.181.220 ansible_user=ubuntu ansible_ssh_private_key_file=/home/heave/.ssh/my-ec2-key
3.210.202.192 ansible_user=ubuntu ansible_ssh_private_key_file=/home/heave/.ssh/my-ec2-key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
[defaults]
inventory = hosts.yml            # or hosts.ini if you switched back
host_key_checking = false